name: DEAP
channels:
- conda-forge
- bioconda
- defaults

dependencies:
# GENERAL
- snakemake=5.4.5
- samtools
- python>=3.8
- r-base>=4
- r-biocmanager
- glib>=2.56

# align_STAR.snakefile
- star=2.5.1b
- star-fusion>=0.5.4
- subread=2.0.6

# rsem.snakefile
- rsem

# trim.snakefile
- trim-galore>=0.6.2

# align_salmon.snakefile
- salmon=0.14.1

# expression.snakefile
# 
# - bioconductor-deseq2>=1.12.1
- bioconductor-limma
# - bioconductor-edger
# - bioconductor-tximport
- bioconductor-org.hs.eg.db
- bioconductor-org.mm.eg.db
- bioconductor-affy
- bioconductor-affyplm
# - bioconductor-sva
# - bioconductor-oligo
- r-optparse
- r-ggplot2>=3.1.1
- r-ggrepel
- r-readr
- r-calibrate
- pydeseq2>=0.4.4
- scipy
- scikit-learn
- pandas
- numpy
- adjusttext # for plot
- matplotlib

#gsea.snakefile
- bioconductor-clusterprofiler
- gseapy

#lisa.snakefile

- pip:
  - inmoose==0.3.0 # 0.3.1 has bug on batch effect, count_pd return array